### ISSUE TITLE
Upgrade to TF 2.0

### ISSUE THREAD

**Issue by maxmstrmn** [chickenjohn/Autopilot-TensorFlow-In-BNN#1]
Please upgrade this code to be used with Tensorflow 2.0. Currently, it is unusable with version higher than 1.14.

**Comment by chickenjohn** [comment]
There's no upgrade plan currently.

**Comment by maxmstrmn** [comment]
What a bummer. I bet you can't upgrade the code, because you just copied it from the others.

**Comment by maxmstrmn** [comment]
Its really disappointing!
